attributes:
  properties:
    name:
      type: string
      title: name
      description: Description of 'name'
      options: {}
    surname:
      type: string
      title: surname
      description: Description of 'surname'
      options: {}
    email:
      type: string
      title: email
      description: Description of 'email'
      options: {}
